<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 1,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            1 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 2,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            2 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Email',
                'edit' => 1,
                'field' => 'email',
                'id' => 3,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            3 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Password',
                'edit' => 1,
                'field' => 'password',
                'id' => 4,
                'order' => 4,
                'read' => 0,
                'required' => 1,
                'type' => 'password',
            ),
            4 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Remember Token',
                'edit' => 0,
                'field' => 'remember_token',
                'id' => 5,
                'order' => 5,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            5 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 6,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            6 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 7,
                'order' => 7,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            7 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Avatar',
                'edit' => 1,
                'field' => 'avatar',
                'id' => 8,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            8 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'user_belongsto_role_relationship',
                'id' => 9,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            9 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'display_name' => 'Roles',
                'edit' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'id' => 10,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            10 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 1,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Settings',
                'edit' => 0,
                'field' => 'settings',
                'id' => 11,
                'order' => 12,
                'read' => 0,
                'required' => 0,
                'type' => 'hidden',
            ),
            11 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 12,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            12 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 2,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 13,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            13 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 14,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            14 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 2,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 15,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            15 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'ID',
                'edit' => 0,
                'field' => 'id',
                'id' => 16,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'number',
            ),
            16 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 17,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            17 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 18,
                'order' => 3,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            18 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 3,
                'delete' => 0,
                'details' => NULL,
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 19,
                'order' => 4,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            19 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 3,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Display Name',
                'edit' => 1,
                'field' => 'display_name',
                'id' => 20,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            20 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 1,
                'delete' => 1,
                'details' => NULL,
                'display_name' => 'Role',
                'edit' => 1,
                'field' => 'role_id',
                'id' => 21,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            21 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 22,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'hidden',
            ),
            22 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 23,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            23 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Slug',
                'edit' => 0,
                'field' => 'slug',
                'id' => 24,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            24 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 25,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            25 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 4,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 26,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            26 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 27,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'hidden',
            ),
            27 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Name',
                'edit' => 1,
                'field' => 'name',
                'id' => 28,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            28 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Slug',
                'edit' => 0,
                'field' => 'slug',
                'id' => 29,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            29 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Details',
                'edit' => 1,
                'field' => 'details',
                'id' => 30,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text_area',
            ),
            30 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
            'details' => '{"validation":{"rule":"required|regex:\\/^\\\\d*(\\\\.\\\\d{1,2})?$\\/"}}',
                'display_name' => 'Price',
                'edit' => 1,
                'field' => 'price',
                'id' => 31,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            31 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Description',
                'edit' => 1,
                'field' => 'description',
                'id' => 32,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text_area',
            ),
            32 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"on":"Yes","off":"No"}',
                'display_name' => 'Featured',
                'edit' => 1,
                'field' => 'featured',
                'id' => 33,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            33 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 34,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'image',
            ),
            34 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Category Id',
                'edit' => 1,
                'field' => 'category_id',
                'id' => 35,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            35 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 36,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            36 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 37,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            37 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Category","table":"categories","type":"belongsTo","column":"category_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'Category',
                'edit' => 1,
                'field' => 'product_belongsto_category_relationship',
                'id' => 38,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            38 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Images',
                'edit' => 1,
                'field' => 'images',
                'id' => 39,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'multiple_images',
            ),
            39 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Order Number',
                'edit' => 0,
                'field' => 'id',
                'id' => 40,
                'order' => 1,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            40 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'User Id',
                'edit' => 0,
                'field' => 'user_id',
                'id' => 41,
                'order' => 2,
                'read' => 0,
                'required' => 0,
                'type' => 'text',
            ),
            41 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Email',
                'edit' => 1,
                'field' => 'billing_email',
                'id' => 42,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            42 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Name',
                'edit' => 1,
                'field' => 'billing_name',
                'id' => 43,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            43 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Address',
                'edit' => 1,
                'field' => 'billing_address',
                'id' => 44,
                'order' => 11,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            44 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing City',
                'edit' => 1,
                'field' => 'billing_city',
                'id' => 45,
                'order' => 12,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            45 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Province',
                'edit' => 1,
                'field' => 'billing_province',
                'id' => 46,
                'order' => 13,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            46 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Postalcode',
                'edit' => 1,
                'field' => 'billing_postalcode',
                'id' => 47,
                'order' => 14,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            47 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Phone',
                'edit' => 1,
                'field' => 'billing_phone',
                'id' => 48,
                'order' => 15,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            48 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Name On Card',
                'edit' => 1,
                'field' => 'billing_name_on_card',
                'id' => 49,
                'order' => 17,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            49 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Discount',
                'edit' => 1,
                'field' => 'billing_discount',
                'id' => 50,
                'order' => 16,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            50 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Discount Code',
                'edit' => 1,
                'field' => 'billing_discount_code',
                'id' => 51,
                'order' => 19,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            51 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Subtotal',
                'edit' => 1,
                'field' => 'billing_subtotal',
                'id' => 52,
                'order' => 18,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            52 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Tax',
                'edit' => 1,
                'field' => 'billing_tax',
                'id' => 53,
                'order' => 20,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            53 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Billing Total',
                'edit' => 1,
                'field' => 'billing_total',
                'id' => 54,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            54 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Payment Gateway',
                'edit' => 1,
                'field' => 'payment_gateway',
                'id' => 55,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            55 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{"on":"Yes","off":"No"}',
                'display_name' => 'Shipped',
                'edit' => 1,
                'field' => 'shipped',
                'id' => 56,
                'order' => 8,
                'read' => 1,
                'required' => 1,
                'type' => 'checkbox',
            ),
            56 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Error',
                'edit' => 1,
                'field' => 'error',
                'id' => 57,
                'order' => 9,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            57 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 58,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            58 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 59,
                'order' => 26,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            59 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'users',
                'edit' => 1,
                'field' => 'order_belongsto_user_relationship',
                'id' => 60,
                'order' => 3,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            60 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 5,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Quantity',
                'edit' => 1,
                'field' => 'quantity',
                'id' => 73,
                'order' => 9,
                'read' => 1,
                'required' => 1,
                'type' => 'number',
            ),
            61 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 74,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'hidden',
            ),
            62 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Code',
                'edit' => 1,
                'field' => 'code',
                'id' => 75,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            63 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"default":"fixed","options":{"fixed":"fixed","percent":"percent"}}',
                'display_name' => 'Type',
                'edit' => 1,
                'field' => 'type',
                'id' => 76,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'radio_btn',
            ),
            64 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Value',
                'edit' => 1,
                'field' => 'value',
                'id' => 77,
                'order' => 4,
                'read' => 1,
                'required' => 0,
                'type' => 'number',
            ),
            65 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Percent Off',
                'edit' => 1,
                'field' => 'percent_off',
                'id' => 78,
                'order' => 5,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            66 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 0,
                'field' => 'created_at',
                'id' => 79,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            67 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 7,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 80,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            68 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|date"}}',
                'display_name' => 'Start At',
                'edit' => 1,
                'field' => 'start_at',
                'id' => 81,
                'order' => 6,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            69 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 7,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|date|after:start_at"}}',
                'display_name' => 'Expire At',
                'edit' => 1,
                'field' => 'expire_at',
                'id' => 82,
                'order' => 7,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            70 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Shipping Address',
                'edit' => 1,
                'field' => 'shipping_address',
                'id' => 83,
                'order' => 21,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            71 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Shipping City',
                'edit' => 1,
                'field' => 'shipping_city',
                'id' => 84,
                'order' => 22,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            72 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Shipping Province',
                'edit' => 1,
                'field' => 'shipping_province',
                'id' => 85,
                'order' => 23,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            73 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Shipping Postalcode',
                'edit' => 1,
                'field' => 'shipping_postalcode',
                'id' => 86,
                'order' => 24,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            74 => 
            array (
                'add' => 1,
                'browse' => 0,
                'data_type_id' => 6,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Shipping Phone',
                'edit' => 1,
                'field' => 'shipping_phone',
                'id' => 87,
                'order' => 25,
                'read' => 1,
                'required' => 0,
                'type' => 'text',
            ),
            75 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Id',
                'edit' => 0,
                'field' => 'id',
                'id' => 88,
                'order' => 1,
                'read' => 0,
                'required' => 1,
                'type' => 'hidden',
            ),
            76 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
            'details' => '{"validation":{"rule":"required|image|mimes:jpeg,png,jpg,gif,svg|dimensions:max_width=1910,max_height=610"},"description":"Preferred dimensions (1770X605) but max width is 1910 and max height is 610"}',
                'display_name' => 'Image',
                'edit' => 1,
                'field' => 'image',
                'id' => 89,
                'order' => 6,
                'read' => 1,
                'required' => 1,
                'type' => 'image',
            ),
            77 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Product Name',
                'edit' => 1,
                'field' => 'product_name',
                'id' => 90,
                'order' => 3,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            78 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Product Price Description',
                'edit' => 1,
                'field' => 'product_price_description',
                'id' => 91,
                'order' => 4,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            79 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Product Stock Status',
                'edit' => 1,
                'field' => 'product_stock_status',
                'id' => 92,
                'order' => 5,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
            80 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Product Id',
                'edit' => 1,
                'field' => 'product_id',
                'id' => 93,
                'order' => 2,
                'read' => 1,
                'required' => 1,
                'type' => 'hidden',
            ),
            81 => 
            array (
                'add' => 0,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{}',
                'display_name' => 'Created At',
                'edit' => 1,
                'field' => 'created_at',
                'id' => 94,
                'order' => 8,
                'read' => 1,
                'required' => 0,
                'type' => 'timestamp',
            ),
            82 => 
            array (
                'add' => 0,
                'browse' => 0,
                'data_type_id' => 8,
                'delete' => 0,
                'details' => '{}',
                'display_name' => 'Updated At',
                'edit' => 0,
                'field' => 'updated_at',
                'id' => 95,
                'order' => 9,
                'read' => 0,
                'required' => 0,
                'type' => 'timestamp',
            ),
            83 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"products","type":"belongsTo","column":"product_id","key":"id","label":"name","pivot_table":"categories","pivot":"0","taggable":"0"}',
                'display_name' => 'products',
                'edit' => 1,
                'field' => 'home_banner_belongsto_product_relationship',
                'id' => 96,
                'order' => 10,
                'read' => 1,
                'required' => 0,
                'type' => 'relationship',
            ),
            84 => 
            array (
                'add' => 1,
                'browse' => 1,
                'data_type_id' => 8,
                'delete' => 1,
                'details' => '{"description":"You can use any color format"}',
                'display_name' => 'Text Color',
                'edit' => 1,
                'field' => 'text_color',
                'id' => 97,
                'order' => 7,
                'read' => 1,
                'required' => 1,
                'type' => 'text',
            ),
        ));
        
        
    }
}