<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-boat',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2021-02-22 01:56:09',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2021-02-23 10:16:50',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2021-03-13 17:41:25',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 01:56:09',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 02:06:42',
                'icon_class' => 'voyager-categories',
                'id' => 11,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2021-02-23 10:16:47',
                'url' => '',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-22 02:08:00',
                'icon_class' => 'voyager-basket',
                'id' => 12,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.products.index',
                'target' => '_self',
                'title' => 'Products',
                'updated_at' => '2021-02-23 10:16:47',
                'url' => '',
            ),
            12 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-02-22 02:17:36',
                'icon_class' => NULL,
                'id' => 17,
                'menu_id' => 3,
                'order' => 2,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'fas fa-globe',
                'updated_at' => '2021-03-23 10:50:59',
                'url' => 'https://abbas-alshaqaq.com/',
            ),
            13 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-02-22 02:18:02',
                'icon_class' => NULL,
                'id' => 18,
                'menu_id' => 3,
                'order' => 3,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'fab fa-twitter',
                'updated_at' => '2021-03-23 10:49:22',
                'url' => 'https://twitter.com/AbbasShDev',
            ),
            14 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-02-22 02:18:26',
                'icon_class' => NULL,
                'id' => 19,
                'menu_id' => 3,
                'order' => 4,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'fab fa-github',
                'updated_at' => '2021-03-23 10:50:25',
                'url' => 'https://github.com/AbbasShDev',
            ),
            15 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-02-22 02:19:01',
                'icon_class' => NULL,
                'id' => 20,
                'menu_id' => 3,
                'order' => 5,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'fab fa-linkedin-in',
                'updated_at' => '2021-03-23 10:50:05',
                'url' => 'https://www.linkedin.com/in/abbas-alshaqaq/',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-02-22 02:19:10',
                'icon_class' => NULL,
                'id' => 21,
                'menu_id' => 3,
                'order' => 1,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Follow Me:',
                'updated_at' => '2021-02-22 02:19:19',
                'url' => '',
            ),
            17 => 
            array (
                'color' => NULL,
                'created_at' => '2021-02-23 10:07:34',
                'icon_class' => 'voyager-documentation',
                'id' => 22,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.orders.index',
                'target' => '_self',
                'title' => 'Orders',
                'updated_at' => '2021-02-23 10:16:50',
                'url' => '',
            ),
            18 => 
            array (
                'color' => NULL,
                'created_at' => '2021-03-12 16:40:26',
                'icon_class' => 'voyager-hook',
                'id' => 23,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.hooks',
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2021-03-16 21:54:09',
                'url' => '',
            ),
            19 => 
            array (
                'color' => NULL,
                'created_at' => '2021-03-13 16:23:12',
                'icon_class' => 'voyager-bolt',
                'id' => 24,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.coupons.index',
                'target' => '_self',
                'title' => 'Coupons',
                'updated_at' => '2021-03-13 17:41:25',
                'url' => '',
            ),
            20 => 
            array (
                'color' => '#000000',
                'created_at' => '2021-03-16 20:44:04',
                'icon_class' => 'voyager-photo',
                'id' => 25,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.home-banners.index',
                'target' => '_self',
                'title' => 'Home Banners',
                'updated_at' => '2021-03-16 21:55:58',
                'url' => '',
            ),
        ));
        
        
    }
}