<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'billing_address' => 'Incididunt cum excep',
                'billing_city' => 'Ut illum eius volup',
                'billing_discount' => 3000,
                'billing_discount_code' => 'ABC123',
                'billing_email' => 'admin@admin.com',
                'billing_name' => 'Yoshio Nichols',
                'billing_name_on_card' => 'Solomon Woodward',
            'billing_phone' => '+1 (167) 775-7216',
                'billing_postalcode' => 'Ullam non vero excep',
                'billing_province' => 'Esse ea ipsum enim',
                'billing_subtotal' => 680518,
                'billing_tax' => 102078,
                'billing_total' => 782596,
                'created_at' => '2021-03-12 22:58:32',
                'error' => NULL,
                'id' => 1,
                'payment_gateway' => 'stripe',
                'shipped' => 1,
                'shipping_address' => '1833 Riverside Drive',
                'shipping_city' => 'Ottawa',
                'shipping_phone' => '6132522672',
                'shipping_postalcode' => 'K1G 0E8',
                'shipping_province' => 'Ontario',
                'updated_at' => '2021-03-12 22:59:01',
                'user_id' => 1,
            ),
            1 => 
            array (
                'billing_address' => NULL,
                'billing_city' => NULL,
                'billing_discount' => 0,
                'billing_discount_code' => '0',
                'billing_email' => NULL,
                'billing_name' => NULL,
                'billing_name_on_card' => NULL,
                'billing_phone' => NULL,
                'billing_postalcode' => NULL,
                'billing_province' => NULL,
                'billing_subtotal' => 81184,
                'billing_tax' => 12178,
                'billing_total' => 93362,
                'created_at' => '2021-03-13 00:10:49',
                'error' => NULL,
                'id' => 2,
                'payment_gateway' => 'paypal',
                'shipped' => 0,
                'shipping_address' => NULL,
                'shipping_city' => NULL,
                'shipping_phone' => NULL,
                'shipping_postalcode' => NULL,
                'shipping_province' => NULL,
                'updated_at' => '2021-03-13 23:20:39',
                'user_id' => 1,
            ),
            2 => 
            array (
                'billing_address' => 'Necessitatibus qui v',
                'billing_city' => 'Sed fugiat repellen',
                'billing_discount' => 0,
                'billing_discount_code' => '0',
                'billing_email' => 'lohyvyl@mailinator.com',
                'billing_name' => 'Lilah Everett',
                'billing_name_on_card' => 'Britanney Lucas',
            'billing_phone' => '+1 (596) 329-9115',
                'billing_postalcode' => 'Recusandae Magni na',
                'billing_province' => 'Qui aut esse nostru',
                'billing_subtotal' => 380426,
                'billing_tax' => 57064,
                'billing_total' => 437490,
                'created_at' => '2021-03-24 06:50:10',
                'error' => NULL,
                'id' => 3,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => NULL,
                'shipping_city' => NULL,
                'shipping_phone' => NULL,
                'shipping_postalcode' => NULL,
                'shipping_province' => NULL,
                'updated_at' => '2021-03-24 06:50:10',
                'user_id' => NULL,
            ),
            3 => 
            array (
                'billing_address' => 'jeididjf',
                'billing_city' => 'ifufh',
                'billing_discount' => 0,
                'billing_discount_code' => '0',
                'billing_email' => 'jfusid@ururu.ruf',
                'billing_name' => 'hiddif',
                'billing_name_on_card' => 'jdududh',
                'billing_phone' => '83747',
                'billing_postalcode' => '73638',
                'billing_province' => 'jdjdu',
                'billing_subtotal' => 145408,
                'billing_tax' => 21811,
                'billing_total' => 167219,
                'created_at' => '2021-03-24 06:53:50',
                'error' => NULL,
                'id' => 4,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => NULL,
                'shipping_city' => NULL,
                'shipping_phone' => NULL,
                'shipping_postalcode' => NULL,
                'shipping_province' => NULL,
                'updated_at' => '2021-03-24 06:53:50',
                'user_id' => NULL,
            ),
            4 => 
            array (
                'billing_address' => 'Irure possimus iste',
                'billing_city' => 'Est in esse iste est',
                'billing_discount' => 100000,
                'billing_discount_code' => 'fixed10',
                'billing_email' => 'abbas20alzaeem@gmail.com',
                'billing_name' => 'Jameson Eaton',
                'billing_name_on_card' => 'Odessa Atkinson',
            'billing_phone' => '+1 (514) 929-8762',
                'billing_postalcode' => 'Voluptas ut exercita',
                'billing_province' => 'Ex excepturi odit co',
                'billing_subtotal' => 575919,
                'billing_tax' => 86388,
                'billing_total' => 662307,
                'created_at' => '2021-03-25 16:51:27',
                'error' => NULL,
                'id' => 5,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Obcaecati ut iusto a',
                'shipping_city' => 'Velit enim voluptas',
            'shipping_phone' => '+1 (227) 933-4657',
                'shipping_postalcode' => 'Qui magni a ipsa as',
                'shipping_province' => 'Officia incididunt u',
                'updated_at' => '2021-03-25 16:51:27',
                'user_id' => 7,
            ),
            5 => 
            array (
                'billing_address' => 'Earum quis nisi ab e',
                'billing_city' => 'Laudantium voluptat',
                'billing_discount' => 0,
                'billing_discount_code' => '0',
                'billing_email' => 'abbas20alzaeem@hotmail.com',
                'billing_name' => 'Odette Henderson',
                'billing_name_on_card' => 'Joel Fields',
            'billing_phone' => '+1 (251) 552-5187',
                'billing_postalcode' => 'Deserunt tempor volu',
                'billing_province' => 'Duis voluptatem Sed',
                'billing_subtotal' => 275292,
                'billing_tax' => 41294,
                'billing_total' => 316586,
                'created_at' => '2021-03-25 16:55:06',
                'error' => NULL,
                'id' => 6,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Obcaecati ut iusto a',
                'shipping_city' => 'Velit enim voluptas',
            'shipping_phone' => '+1 (227) 933-4657',
                'shipping_postalcode' => 'Qui magni a ipsa as',
                'shipping_province' => 'Officia incididunt u',
                'updated_at' => '2021-03-25 16:55:06',
                'user_id' => 7,
            ),
            6 => 
            array (
                'billing_address' => 'Ipsum enim est non',
                'billing_city' => 'Nam ut Nam in est q',
                'billing_discount' => 100000,
                'billing_discount_code' => 'fixed10',
                'billing_email' => 'abbas20alzaeem@hotmail.com',
                'billing_name' => 'Kareem Morris',
                'billing_name_on_card' => 'Wyoming Camacho',
            'billing_phone' => '+1 (614) 255-7743',
                'billing_postalcode' => 'Dolorem dolor molest',
                'billing_province' => 'Et eius dignissimos',
                'billing_subtotal' => 201167,
                'billing_tax' => 30175,
                'billing_total' => 231342,
                'created_at' => '2021-03-26 09:55:09',
                'error' => NULL,
                'id' => 7,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Obcaecati ut iusto a',
                'shipping_city' => 'Velit enim voluptas',
            'shipping_phone' => '+1 (227) 933-4657',
                'shipping_postalcode' => 'Qui magni a ipsa as',
                'shipping_province' => 'Officia incididunt u',
                'updated_at' => '2021-03-26 09:55:09',
                'user_id' => 7,
            ),
            7 => 
            array (
                'billing_address' => '307 Southcrest private',
                'billing_city' => 'Ottawa',
                'billing_discount' => 100000,
                'billing_discount_code' => 'fixed10',
                'billing_email' => 'abbas20alzaeem@hotmail.com',
                'billing_name' => 'ABBAS ALSHAQAQ',
                'billing_name_on_card' => 'Abbas Alshaqaq',
                'billing_phone' => '6132522672',
                'billing_postalcode' => 'K1V2B7',
                'billing_province' => 'ON',
                'billing_subtotal' => 175292,
                'billing_tax' => 26294,
                'billing_total' => 201586,
                'created_at' => '2021-03-26 10:00:13',
                'error' => NULL,
                'id' => 8,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Obcaecati ut iusto a',
                'shipping_city' => 'Velit enim voluptas',
            'shipping_phone' => '+1 (227) 933-4657',
                'shipping_postalcode' => 'Qui magni a ipsa as',
                'shipping_province' => 'Officia incididunt u',
                'updated_at' => '2021-03-26 10:00:13',
                'user_id' => 7,
            ),
            8 => 
            array (
                'billing_address' => '1833 Riverside Drive',
                'billing_city' => 'Ottawa',
                'billing_discount' => 100000,
                'billing_discount_code' => 'fixed10',
                'billing_email' => 'abbas20alzaeem@hotmail.com',
                'billing_name' => 'Abbas Alshaqaq',
                'billing_name_on_card' => 'Abbas Alshaqaq',
                'billing_phone' => '6132522672',
                'billing_postalcode' => 'K1G 0E8',
                'billing_province' => 'Ontario',
                'billing_subtotal' => 6983,
                'billing_tax' => 1047,
                'billing_total' => 8030,
                'created_at' => '2021-03-26 10:01:37',
                'error' => NULL,
                'id' => 9,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Obcaecati ut iusto a',
                'shipping_city' => 'Velit enim voluptas',
            'shipping_phone' => '+1 (227) 933-4657',
                'shipping_postalcode' => 'Qui magni a ipsa as',
                'shipping_province' => 'Officia incididunt u',
                'updated_at' => '2021-03-26 10:01:37',
                'user_id' => 7,
            ),
            9 => 
            array (
                'billing_address' => 'Id quas iste volupt',
                'billing_city' => 'Eos aut excepturi c',
                'billing_discount' => 0,
                'billing_discount_code' => '0',
                'billing_email' => 'abbas20alzaeem@hotmail.com',
                'billing_name' => 'Sydnee Foster',
                'billing_name_on_card' => 'Odessa Ramsey',
            'billing_phone' => '+1 (194) 572-5619',
                'billing_postalcode' => 'Totam fugiat dolore',
                'billing_province' => 'Nostrud tempora aut',
                'billing_subtotal' => 427791,
                'billing_tax' => 64169,
                'billing_total' => 491960,
                'created_at' => '2021-03-26 10:07:00',
                'error' => NULL,
                'id' => 10,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Obcaecati ut iusto a',
                'shipping_city' => 'Velit enim voluptas',
            'shipping_phone' => '+1 (227) 933-4657',
                'shipping_postalcode' => 'Qui magni a ipsa as',
                'shipping_province' => 'Officia incididunt u',
                'updated_at' => '2021-03-26 10:07:00',
                'user_id' => 7,
            ),
            10 => 
            array (
                'billing_address' => 'Elit eaque harum ha',
                'billing_city' => 'Dolorum tempora Nam',
                'billing_discount' => 100000,
                'billing_discount_code' => 'fixed10',
                'billing_email' => 'JohnDoe@laramerce.me',
                'billing_name' => 'Alika Adkins',
                'billing_name_on_card' => 'Wanda Woods',
            'billing_phone' => '+1 (739) 968-1168',
                'billing_postalcode' => 'Velit est magni quis',
                'billing_province' => 'Iste ut nesciunt no',
                'billing_subtotal' => 676130,
                'billing_tax' => 101420,
                'billing_total' => 777550,
                'created_at' => '2021-04-09 14:56:51',
                'error' => NULL,
                'id' => 11,
                'payment_gateway' => 'stripe',
                'shipped' => 0,
                'shipping_address' => 'Consequatur dolor u',
                'shipping_city' => 'Laborum Nostrud mol',
            'shipping_phone' => '+1 (584) 339-9185',
                'shipping_postalcode' => 'Id voluptatem Dolor',
                'shipping_province' => 'Velit veniam magni',
                'updated_at' => '2021-04-09 14:56:51',
                'user_id' => 8,
            ),
        ));
        
        
    }
}